before_commands:
    - composer install --dev
tools:
    php_sim: true
    php_pdepend:
        enabled: true
    php_analzyer:
        enabled: true
    php_changetracking: true
    php_mess_detector:
        enabled: true
    sensiolabs_security_checker: true
    php_cs_fixer:
        extensions:
            - php
        command: php-cs-fixer
        enabled: true
        filter:
            excluded_paths: ["vendor", "node_modules"]
            paths: ["*.php"]
        config:
            level: psr2
    php_cpd:
        command: phpcpd
        min_lines: 5
        min_tokens: 70
        names:
            - '*.php'
        excluded_dirs: ["vendor", "node_modules"]
        enabled: true
    php_code_sniffer:
        extensions:
            - php
        command: phpcs
        enabled: true
        filter:
            excluded_paths: ["vendor", "node_modules"]
            paths: ["*.php"]
        config:
            standard: PSR2
